//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApk.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Id_admin { get; set; }
        public string Name { get; set; }
        public int Id_login { get; set; }
    
        public virtual Login Login { get; set; }

        public override bool Equals(Object obj)
        {
            if ((obj == null) || !this.GetType().Equals(obj.GetType()))
            {
                return false;
            }
            else
            {
                Admin sec = (Admin)obj;
                return (Id_admin == sec.Id_admin) && (Name == sec.Name) && (Id_login == sec.Id_login);
            }
        }
    }
}
