//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApk.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.Sessions = new HashSet<Session>();
        }
    
        public int Id_class { get; set; }
        public int Id_branch { get; set; }
        public System.DateTime Commencment_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
        public string Name { get; set; }
    
        public virtual Branch_type Branch_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
        public override bool Equals(Object obj)
        {
            if ((obj == null) || !this.GetType().Equals(obj.GetType()))
            {
                return false;
            }
            else
            {
                Class sec = (Class)obj;
                return (Id_class == sec.Id_class) && (Name == sec.Name) && (Id_branch == sec.Id_branch) && (Commencment_date == sec.Commencment_date) && (End_date == sec.End_date);
            }
        }
    }
}
