//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApk.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int Id_grade { get; set; }
        public int Id_lecturer { get; set; }
        public int Id_subject { get; set; }
        public int Id_student { get; set; }
        public System.DateTime Grade_date { get; set; }
        public int Grade1 { get; set; }
    
        public virtual Lecturer Lecturer { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }

        public override bool Equals(Object obj)
        {
            if ((obj == null) || !this.GetType().Equals(obj.GetType()))
            {
                return false;
            }
            else
            {
                Grade sec = (Grade)obj;
                return (Id_grade == sec.Id_grade) && (Id_lecturer == sec.Id_lecturer) && (Id_subject == sec.Id_subject) && (Id_student == sec.Id_student) && (Grade_date == sec.Grade_date) && (Grade1 == sec.Grade1);
            }
        }
    }
}
