//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApk.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int Id_session { get; set; }
        public int Id_student { get; set; }
        public int Id_class { get; set; }
        public System.DateTime Start_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
        public int Nr_session { get; set; }
        public Nullable<int> Part_session { get; set; }
        public Nullable<bool> Pass { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
    }
}
