//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApk.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Sessions = new HashSet<Session>();
            this.Stipends = new HashSet<Stipend>();
            this.Grades = new HashSet<Grade>();
        }
    
        public int Id_student { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Address { get; set; }
        public System.DateTime Birth_date { get; set; }
        public System.DateTime Entrance_date { get; set; }
        public Nullable<System.DateTime> Leaving_date { get; set; }
        public Nullable<bool> Stipend { get; set; }
        public int Id_login { get; set; }
    
        public virtual Login Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stipend> Stipends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grades { get; set; }

        public override bool Equals(Object obj)
        {
            if ((obj == null) || !this.GetType().Equals(obj.GetType()))
            {
                return false;
            }
            else
            {
                Student sec = (Student)obj;
                return (Id_student == sec.Id_student) && (First_name == sec.First_name) && (Last_name == sec.Last_name) && (Address == sec.Address) && (Birth_date == sec.Birth_date) && (Entrance_date == sec.Entrance_date) &&
                    (Leaving_date == sec.Leaving_date) && (Stipend == sec.Stipend) && (Id_login == sec.Id_login);
            }
        }
    }
}
